# Generated by Django 2.2.8 on 2019-12-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='Владивосток', max_length=128, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, default='ул. Адмирала Юмашева 35', max_length=128, null=True, verbose_name='Улица, дом')),
                ('email', models.CharField(blank=True, default='konfetti@mail.ru', max_length=128, null=True, verbose_name='Email')),
                ('phone1', models.CharField(blank=True, default='89510183672', max_length=128, null=True, verbose_name='Телефон 1')),
                ('phone2', models.CharField(blank=True, default='89146773888', max_length=128, null=True, verbose_name='Телефон 2')),
                ('working_hours', models.CharField(blank=True, default='пн-пт 9-17, сб-вс: 9-14', max_length=128, null=True, verbose_name='Часы работы')),
                ('map', models.TextField(blank=True, max_length=500, null=True, verbose_name='Код яндекс карты')),
                ('whatsapp', models.CharField(blank=True, max_length=128, null=True, verbose_name='WhatsApp')),
                ('viber', models.CharField(blank=True, max_length=128, null=True, verbose_name='Viber')),
                ('telegram', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram')),
                ('vk', models.CharField(blank=True, max_length=128, null=True, verbose_name='Vkontakte')),
                ('instagram', models.CharField(blank=True, max_length=128, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=128, null=True, verbose_name='Facebook')),
                ('price_list', models.FileField(upload_to='static/pricelist/', verbose_name='Прайс')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
