# Generated by Django 2.2.8 on 2019-12-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='price_list',
            field=models.FileField(blank=True, upload_to='static/pricelist/', verbose_name='Прайс'),
        ),
    ]
