# Generated by Django 2.2.8 on 2019-12-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=512, verbose_name='Текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='На главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуален')),
            ],
            options={
                'verbose_name': 'Идея',
                'verbose_name_plural': 'Идеи',
            },
        ),
    ]
