# Generated by Django 2.2.8 on 2019-12-04 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/products/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='idea',
            name='image_thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='static/img/products/'),
        ),
    ]
