# Generated by Django 2.2.8 on 2019-12-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('text', models.TextField(max_length=512, verbose_name='Отзыв')),
                ('image', models.ImageField(blank=True, upload_to='static/img/reviews/', verbose_name='Изображение')),
                ('image_thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/reviews/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуален')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
