# Generated by Django 2.2.8 on 2019-12-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Имя')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('t', models.CharField(max_length=128, verbose_name='Тип')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
