# Generated by Django 2.2.8 on 2019-12-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191202_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'id': 'self.id'}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category', verbose_name='Родительская категория'),
        ),
    ]
