# Generated by Django 2.2.8 on 2019-12-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191202_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category', verbose_name='Родительская категория'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='static/img/products/', verbose_name='Изображение')),
                ('image_thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/products/')),
                ('is_main', models.BooleanField(default=False, verbose_name='На главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуален')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
