# Generated by Django 2.2.8 on 2019-12-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191203_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_category_children_+', to='products.Category', verbose_name='Дочерние категории'),
        ),
    ]
