# Generated by Django 2.2.8 on 2019-12-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191203_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='products.Category', verbose_name='Родительские категория'),
        ),
    ]
