# Generated by Django 2.2.8 on 2019-12-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191204_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=True, verbose_name='Популярный товар'),
        ),
    ]
